server:
  port: 8084

spring:
  application:
    name: medical-record-service
  datasource:
    url: jdbc:mysql://localhost:3306/medical_record_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
