apiVersion: apps/v1
kind: Deployment
metadata:
  name: practitioner-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practitioner-service
  template:
    metadata:
      labels:
        app: practitioner-service
    spec:
      containers:
        - name: practitioner-service
          image: practitioner-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: practitioner-service
spec:
  selector:
    app: practitioner-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: LoadBalancer
