server:
  port: 8083

spring:
  application:
    name: appointment-service
  datasource:
    url: jdbc:mysql://localhost:3306/appointment_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
